spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT   该配置可以用于 SpringBoot 2.4.5
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: 'root'
    password: 'root'
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: wall,stat