spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT   该配置可以用于 SpringBoot 2.4.5
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: 'root'
    password: 'root'
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: wall,stat
    # config StatViewServlet
    druid:
      # 配置监控页功能
      stat-view-servlet:
        # stat-view-servlet-enabled default : false
        enabled: true
        login-username: druid
        login-password: druid
        # resetEnable default true
        reset-enable: false
        #如果allow没有配置或者为空，则允许所有访问
        allow: 127.0.0.1,192.168.2.111  #IP白名单(没有配置或者为空，则允许所有访问)。允许谁访问druid后台，默认允许全部用户访问。
        #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。
        deny: 1.1.1.1 #IP黑名单
      # monitor web application
      web-stat-filter:
        # web-stat-filter-enabled default : false
        enabled: true
        # 匹配哪些地址
        url-pattern: "/*"
        # 排除哪些
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # 底层Spring开启的功能  stat - sql监控功能，  wall - 防火墙监控功能
      filters: "wall,stat,slf4j"
      filter:
        stat:
          # 配置慢查询sql日志（记录慢查询）
          log-slow-sql: true
          # 大于10毫秒的都属于慢查询（筛选哪些sql是慢查询）
          slow-sql-millis: 10
          enabled: true
        wall:
          enabled: true
          config:
            # 不允许删表
            drop-table-allow: false
      #SpringBean监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      #aop-patterns: com.zichen.admin.*

      #配置的格式
      #<IP>
      #或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
      #24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。

# 使用默认配置的aop功能，druid的spring监控功能是空白
# 自己重写aop配置类，结果是可以的
my:
  spring:
    datasource:
      druid:
        aop-patterns: com.zichen.admin.*

#mybatis config
mybatis:
  #mybatis global config
  config-location: classpath:mybatis/mybatis-config.xml
  #mybatis mapper config
  mapper-locations: classpath:mybatis/mapper/UserTbMapper.xml
