spring:
#  mvc:
#    # 访问静态资源添加前缀，静态资源前缀对于访问欢迎页不支持，因为底层已经写死了，直接找静态资源下的index.html
#    static-path-pattern: /res/**
  web:
    resources:
      # 改变静态资源访问路径
      #static-locations: classpath:/haha/
      # 改变资源访问路径可以使用数组，改变多个资源访问路径
      static-locations: ["classpath:/haha/", "classpath:/abc/", "classpath:/templates"]
      # false是禁用静态资源，都访问不了了，  默认是true不禁用
      # add-mappings: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    # 开启基于请求参数的内容协商，请求参数携带参数format 开决定返回什么数据
    contentnegotiation:
      favor-parameter: true